services:
  db:
    container_name: board-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: board
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "9307:3306"
